version: '3.9'

services:
  cod-result-processor:
    build:
      context: .
    image: cod-result-processor:development
    env_file:
      - .env.development
    environment:
      - MESSENGER_PROVIDER=${MESSENGER_PROVIDER:-telegram}
    container_name: cod-result-processor
    restart: unless-stopped
    volumes:
      - .:/app
    command: watchmedo auto-restart --directory=./ --pattern="*.py" --recursive -- python -u main.py

  wwebjs-api:
    image: avoylenko/wwebjs-api:latest
    container_name: wwebjs-api
    profiles:
      - whatsapp
    ports:
      - "3000:3000"
    environment:
      - BASE_WEBHOOK_URL=http://cod-result-processor:5000/webhook
      - ENABLE_WEBHOOK=TRUE
    volumes:
      - ./sessions:/usr/src/app/sessions
    restart: unless-stopped
